const promoErratas = [7];
const fellowshipOfTheRingErratas = [3, 12, 43, 46, 55, 109, 113, 138, 162, 211, 235, 263, 309, 318, 331, 338, 343, 360];
const minesOfMoriaErratas = [];
const realmOfTheElfLordsErratas = [48, 110];
const twoTowersErratas = [63, 236, 237, 352];
const battleOfHelmsDeepErratas = [];
const entsOfFangornErroatas = [39, 46, 85];
const returnOfTheKingErratas = [10, 14, 66, 114, 133, 134, 135, 182, 284, 285, 289, 302, 357];
const siegeOfGondorErratas = [20, 33, 69];
const reflectionsErratas = [];
const mtDoomErratas = [];
const shadowsErratas = [];
const blackRiderErratas = [];
const bloodlinesErratas = [];
const expandedMiddleEarthErratas = [];
const huntersErratas = [];
const wraithCollectionErratas = [];
const riseOfSarumanErratas = [15, 87, 96, 118];
const treacheryAndDeceitErratas = [8, 12, 20, 25, 35, 48, 50, 55, 77, 78, 79, 80, 82, 94, 97, 133];
const agesEndErratas = [];

export const errataCardList: Map<number, number[]> = new Map();
errataCardList.set(0, promoErratas);
errataCardList.set(1, fellowshipOfTheRingErratas);
errataCardList.set(2, minesOfMoriaErratas);
errataCardList.set(3, realmOfTheElfLordsErratas);
errataCardList.set(4, twoTowersErratas);
errataCardList.set(5, battleOfHelmsDeepErratas);
errataCardList.set(6, entsOfFangornErroatas);
errataCardList.set(7, returnOfTheKingErratas);
errataCardList.set(8, siegeOfGondorErratas);
errataCardList.set(9, reflectionsErratas);
errataCardList.set(10, mtDoomErratas);
errataCardList.set(11, shadowsErratas);
errataCardList.set(12, blackRiderErratas);
errataCardList.set(13, bloodlinesErratas);
errataCardList.set(14, expandedMiddleEarthErratas);
errataCardList.set(15, huntersErratas);
errataCardList.set(16, wraithCollectionErratas);
errataCardList.set(17, riseOfSarumanErratas);
errataCardList.set(18, treacheryAndDeceitErratas);
errataCardList.set(19, agesEndErratas);
